"""Generate all AI/ML teaching notebooks."""
import json, uuid, os

def cell_id():
    return uuid.uuid4().hex[:8]

def md(source_lines):
    return {
        "cell_type": "markdown",
        "id": cell_id(),
        "metadata": {},
        "source": source_lines,
    }

def code(source_lines):
    return {
        "cell_type": "code",
        "id": cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }

def lines(*args):
    """Join lines: each string becomes one line.  Last line has no \\n."""
    result = []
    for i, s in enumerate(args):
        result.append(s + "\n" if i < len(args) - 1 else s)
    return result

def notebook(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11.0"},
        },
        "cells": cells,
    }

def save(path, nb):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"  wrote {os.path.basename(path)}")

BASE = "/home/runner/work/techleaders/techleaders"

# =============================================================================
# 01 — Rule-Based AI
# =============================================================================
nb01 = notebook([
    md(lines(
        "# 01 — Rule-Based AI",
        "",
        "## What *is* artificial intelligence?",
        "",
        "Before machine learning existed, programmers wrote AI **by hand**.  ",
        "They observed patterns in data and translated them into `IF / ELSE` rules.",
        "",
        "This is called a **rule-based system** (or *expert system*).  ",
        "It can work surprisingly well — but someone has to write every single rule.",
        "",
        "In this notebook we build two small rule-based classifiers:",
        "1. An **animal classifier** based on physical traits",
        "2. A **spam detector** based on suspicious keywords",
    )),
    # ---- Animal classifier ----
    md(lines(
        "## Animal Classifier",
        "",
        "A biologist gave us these rules:",
        "",
        "| Observation | Classification |",
        "|-------------|----------------|",
        "| Has feathers | bird |",
        "| Has scales **and** lives in water | fish |",
        "| Has fur **and** warm-blooded | mammal |",
        "| None of the above | unknown |",
        "",
        "We translate those observations directly into Python `if` statements.",
    )),
    code(lines(
        "def classify_animal(has_feathers, has_scales, has_fur, lives_in_water, warm_blooded):",
        '    """Classify an animal using hand-written rules."""',
        "    if has_feathers:",
        '        return "bird"',
        "    if has_scales and lives_in_water:",
        '        return "fish"',
        "    if has_fur and warm_blooded:",
        '        return "mammal"',
        '    return "unknown"',
        "",
        "",
        "animals = [",
        "    # name              feathers  scales   fur    water  warm",
        '    ("Eagle",           True,     False,   False, False, True),',
        '    ("Salmon",          False,    True,    False, True,  False),',
        '    ("Dog",             False,    False,   True,  False, True),',
        '    ("Mystery beast",   False,    False,   False, False, False),',
        "]",
        "",
        'print("Rule-Based Animal Classifier")',
        'print("=" * 35)',
        "for name, *features in animals:",
        "    result = classify_animal(*features)",
        '    print(f"  {name:<20} → {result}")',
    )),
    # ---- Spam classifier ----
    md(lines(
        "## Spam Detector",
        "",
        "Same idea applied to email text.  ",
        "If a message contains **two or more** suspicious keywords, we call it spam.",
        "",
        "This is literally how early spam filters worked — and they caught *a lot* of spam!",
    )),
    code(lines(
        'SPAM_WORDS = ["free", "winner", "click here", "guarantee", "limited offer"]',
        "",
        "def is_spam(email_text: str) -> bool:",
        '    """Simple spam detector using keyword rules."""',
        "    text = email_text.lower()",
        "    matches = [word for word in SPAM_WORDS if word in text]",
        "    return len(matches) >= 2",
        "",
        "",
        "emails = [",
        '    "Hi, are you free for lunch tomorrow?",',
        '    "FREE winner! Click here for your guaranteed limited offer prize!",',
        '    "Your invoice is attached. Please review.",',
        '    "CLICK HERE for a free limited offer — you are the winner!",',
        "]",
        "",
        'print("Spam Classifier")',
        'print("=" * 35)',
        "for email in emails:",
        '    label = "SPAM" if is_spam(email) else "OK  "',
        '    preview = email[:45] + "..." if len(email) > 45 else email',
        '    print(f"  [{label}]  {preview}")',
    )),
    # ---- Key lesson ----
    md(lines(
        "## Key Lesson",
        "",
        "Rule-based systems are:",
        "",
        "- ✅ **Transparent** — you can read every decision the program makes",
        "- ✅ **Fast** to build for simple problems",
        "- ❌ **Brittle** — add a new animal and you need new rules",
        "- ❌ **Hard to scale** — real-world problems have thousands of edge cases",
        "",
        "**Machine learning** flips this around: instead of writing rules,  ",
        "we show the computer thousands of examples and let it *discover* the rules itself.",
        "",
        "That's what the rest of this course is about. 🚀",
    )),
])
save(f"{BASE}/01_rule_based.ipynb", nb01)

# =============================================================================
# 02 — Linear Regression
# =============================================================================
nb02 = notebook([
    md(lines(
        "# 02 — Linear Regression: Learning a Line from Data",
        "",
        "## The Big Idea",
        "",
        "We have a cloud of points `(x, y)`.  ",
        "We want to find the **straight line** `y = w·x + b` that fits them best.",
        "",
        "Two numbers control the line:",
        "- **w** (weight / slope) — how steeply the line rises",
        "- **b** (bias / intercept) — where the line crosses the y-axis",
        "",
        "We start with a random guess, measure how wrong we are, then nudge  ",
        "the line in the right direction — over and over.  That process is called  ",
        "**gradient descent**, and it is the engine behind all of modern AI.",
    )),
    # Step 1 — data
    md(lines(
        "## Step 1 — Generate & Visualise the Data",
        "",
        "We create 30 points that follow `y = 10·x + 30` with a bit of random noise  ",
        "added — like real-world measurements.",
    )),
    code(lines(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "%matplotlib inline",
        "",
        "np.random.seed(42)",
        "x = np.linspace(0, 10, 30)          # 30 evenly-spaced x values from 0 to 10",
        "y = 10 * x + 30 + np.random.randn(30) * 8   # true line + noise",
        "",
        "plt.figure(figsize=(8, 4))",
        'plt.scatter(x, y, color="steelblue", zorder=3, label="data points")',
        'plt.xlabel("x")',
        'plt.ylabel("y")',
        'plt.title("Our Dataset")',
        "plt.legend()",
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Step 2 — initial line
    md(lines(
        "## Step 2 — Start with a Flat Line (w = 0, b = 0)",
        "",
        "Before learning anything our model predicts `y = 0` for every `x`.  ",
        "Plotting it on top of the data shows just how wrong we start.",
    )),
    code(lines(
        "w = 0.0   # slope — starts flat",
        "b = 0.0   # intercept — starts at zero",
        "",
        "x_line = np.array([0, 10])",
        "y_line = w * x_line + b",
        "",
        "plt.figure(figsize=(8, 4))",
        'plt.scatter(x, y, color="steelblue", zorder=3, label="data points")',
        'plt.plot(x_line, y_line, color="red", linewidth=2, label=f"initial line  w={w}, b={b}")',
        'plt.xlabel("x")',
        'plt.ylabel("y")',
        'plt.title("Data + Initial (terrible) Line")',
        "plt.legend()",
        "plt.tight_layout()",
        "plt.show()",
        "",
        'print("The red line is completely flat — it hasn\'t learned anything yet.")',
    )),
    # Step 3 — loss
    md(lines(
        "## Step 3 — Measuring How Wrong We Are (the Loss Function)",
        "",
        "For each data point we compute the **error**: predicted value minus true value.",
        "",
        "We square each error (to make negatives positive and punish big errors more),  ",
        "then take the average.  This is called **Mean Squared Error (MSE)**:",
        "",
        "```",
        "MSE = average( (predicted - actual)² )",
        "```",
        "",
        "A perfect fit has MSE = 0.  A terrible fit has a huge MSE.",
    )),
    code(lines(
        "def compute_loss(w, b, x, y):",
        "    predictions = w * x + b",
        "    errors = predictions - y",
        "    return (errors ** 2).mean()",
        "",
        "initial_loss = compute_loss(0.0, 0.0, x, y)",
        'print(f"Loss with flat line (w=0, b=0): {initial_loss:.1f}")',
        "avg_error = initial_loss ** 0.5",
        'print(f"Each data point is off by roughly: {avg_error:.1f} units on average")',
    )),
    # Step 4 — gradient descent explained
    md(lines(
        "## Step 4 — Gradient Descent: Nudging the Line in the Right Direction",
        "",
        "The key question: **which way should we move `w` and `b`?**",
        "",
        "We compute the **gradient** — how much the loss changes if we  ",
        "increase `w` or `b` slightly.  Then we move in the *opposite* direction  ",
        "(downhill on the loss surface).",
        "",
        "### The gradient formulas (from calculus)",
        "",
        "After differentiating MSE with respect to `w` and `b`:",
        "",
        "```",
        "grad_w = (2/n) * sum( errors * x )   ← each error is weighted by x",
        "grad_b = (2/n) * sum( errors )        ← b shifts all predictions equally",
        "```",
        "",
        "Then we take a small step:",
        "",
        "```",
        "w ← w - learning_rate * grad_w",
        "b ← b - learning_rate * grad_b",
        "```",
        "",
        "The **learning rate** controls step size. Too large → overshoots;  ",
        "too small → learns very slowly.  We'll use `0.01`.",
    )),
    # Step 5 — training with snapshots
    md(lines(
        "## Step 5 — Training Loop: Watch the Line Move",
        "",
        "We run 200 update steps and capture the line at key moments  ",
        "so we can watch it converge toward the true relationship.",
    )),
    code(lines(
        "w = 0.0",
        "b = 0.0",
        "learning_rate = 0.01",
        "n = len(x)",
        "loss_history = []",
        "",
        "# Steps at which we'll take a snapshot of the line",
        "snapshot_steps = {0, 5, 20, 50, 100, 199}",
        "snapshots = []   # list of (step, w, b)",
        "",
        "for step in range(200):",
        "    predictions = w * x + b",
        "    errors = predictions - y          # positive → predicted too high",
        "",
        "    # Gradient of w: weight each error by how much x contributed",
        "    grad_w = (2 / n) * (errors * x).sum()",
        "",
        "    # Gradient of b: b shifts every prediction by the same amount",
        "    grad_b = (2 / n) * errors.sum()",
        "",
        "    # Move opposite to the gradient",
        "    w -= learning_rate * grad_w",
        "    b -= learning_rate * grad_b",
        "",
        "    loss_history.append(compute_loss(w, b, x, y))",
        "",
        "    if step in snapshot_steps:",
        "        snapshots.append((step + 1, w, b))",
        "",
        "# ---- Plot the snapshots ----",
        "fig, ax = plt.subplots(figsize=(9, 5))",
        'ax.scatter(x, y, color="steelblue", zorder=3, label="data")',
        "",
        "colors = plt.cm.plasma(np.linspace(0.1, 0.9, len(snapshots)))",
        "x_line = np.array([0, 10])",
        "for (step, ws, bs), color in zip(snapshots, colors):",
        "    y_line = ws * x_line + bs",
        '    ax.plot(x_line, y_line, color=color, linewidth=2, label=f"step {step}  (w={ws:.1f}, b={bs:.1f})")',
        "",
        'ax.set_xlabel("x")',
        'ax.set_ylabel("y")',
        'ax.set_title("Line evolving over 200 training steps")',
        "ax.legend(loc='upper left', fontsize=8)",
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Step 6 — results and loss curve
    md(lines(
        "## Step 6 — Final Result & Loss Curve",
        "",
        "How close did we get to the true parameters `w=10, b=30`?",
    )),
    code(lines(
        "print(f'Learned:  y = {w:.2f} * x + {b:.2f}')",
        "print(f'Truth:    y = 10.00 * x + 30.00')",
        "print(f'Final loss: {loss_history[-1]:.2f}')",
        "",
        "plt.figure(figsize=(8, 3))",
        'plt.plot(loss_history, color="crimson")',
        'plt.xlabel("Training step")',
        'plt.ylabel("MSE loss")',
        'plt.title("Loss curve — shrinking as the model learns")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    md(lines(
        "## Key Lessons",
        "",
        "1. **w and b** are the only two numbers our model learns — yet that's enough  ",
        "   to capture a linear relationship.",
        "2. **Gradient descent** uses calculus to figure out which direction to nudge  ",
        "   the parameters — no guessing needed.",
        "3. The **loss curve** always decreasing is a healthy sign; if it bounces around  ",
        "   the learning rate is probably too high.",
        "4. This same mechanism — compute loss → compute gradients → update parameters —  ",
        "   is used in **every** neural network, including GPT.",
    )),
])
save(f"{BASE}/02_linear_regression.ipynb", nb02)

# =============================================================================
# 03 — Perceptron
# =============================================================================
nb03 = notebook([
    md(lines(
        "# 03 — The Perceptron: A Single Artificial Neuron",
        "",
        "## Biological inspiration",
        "",
        "A real neuron receives signals from many neighbours, adds them up,  ",
        "and *fires* (sends a signal onward) only when the total is strong enough.",
        "",
        "An artificial neuron does the same thing mathematically:",
        "",
        "```",
        "z    = w₁·x₁ + w₂·x₂ + ... + b      ← weighted sum + bias",
        "output = sigmoid(z)                    ← squash to a probability (0 – 1)",
        "```",
        "",
        "The **weights** `w` say how much each input matters.  ",
        "The **bias** `b` shifts the threshold.",
        "",
        "We'll train a single neuron to learn two simple logic gates: **OR** and **AND**.",
    )),
    # sigmoid
    md(lines(
        "## The Sigmoid Activation Function",
        "",
        "The sigmoid squashes any number into the range (0, 1):",
        "",
        "```",
        "sigmoid(z) = 1 / (1 + e^{-z})",
        "```",
        "",
        "- Very negative z → output near 0  (neuron is *off*)",
        "- Near-zero z     → output near 0.5  (uncertain)",
        "- Very positive z → output near 1  (neuron is *on*)",
        "",
        "Let's plot it.",
    )),
    code(lines(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "%matplotlib inline",
        "",
        "def sigmoid(z):",
        "    return 1 / (1 + np.exp(-z))",
        "",
        "def sigmoid_derivative(z):",
        "    s = sigmoid(z)",
        "    return s * (1 - s)",
        "",
        "z_vals = np.linspace(-6, 6, 200)",
        "",
        "plt.figure(figsize=(8, 3))",
        'plt.plot(z_vals, sigmoid(z_vals), color="darkorange", linewidth=2, label="sigmoid(z)")',
        'plt.axhline(0.5, color="gray", linestyle="--", linewidth=1)',
        'plt.axvline(0, color="gray", linestyle="--", linewidth=1)',
        'plt.xlabel("z  (weighted sum)")',
        'plt.ylabel("output")',
        'plt.title("Sigmoid function — maps any number to (0, 1)")',
        "plt.legend()",
        "plt.tight_layout()",
        "plt.show()",
    )),
    # OR gate dataset
    md(lines(
        "## The OR Gate Dataset",
        "",
        "OR is true when *at least one* input is 1:",
        "",
        "| A | B | A OR B |",
        "|---|---|--------|",
        "| 0 | 0 |   0    |",
        "| 0 | 1 |   1    |",
        "| 1 | 0 |   1    |",
        "| 1 | 1 |   1    |",
        "",
        "These 4 rows are our entire training set.",
    )),
    code(lines(
        "# Each row is one training example: [input_A, input_B]",
        "X = np.array([[0, 0],",
        "              [0, 1],",
        "              [1, 0],",
        "              [1, 1]])",
        "",
        "y_or = np.array([0, 1, 1, 1])   # expected output for OR",
        "",
        "# Visualise the four points",
        "plt.figure(figsize=(4, 4))",
        "for (a, b), label in zip(X, y_or):",
        '    color = "green" if label == 1 else "red"',
        '    marker = "o" if label == 1 else "s"',
        "    plt.scatter(a, b, c=color, marker=marker, s=120, zorder=3)",
        "",
        "# Legend proxies",
        "import matplotlib.patches as mpatches",
        'plt.legend(handles=[mpatches.Patch(color="green", label="OR = 1"),',
        '                     mpatches.Patch(color="red",   label="OR = 0")])',
        'plt.xlim(-0.3, 1.3); plt.ylim(-0.3, 1.3)',
        'plt.xticks([0, 1]); plt.yticks([0, 1])',
        'plt.xlabel("Input A"); plt.ylabel("Input B")',
        'plt.title("OR gate — can a straight line separate the classes?")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Matrix math explanation
    md(lines(
        "## Matrix Notation: Processing All Examples at Once",
        "",
        "For **one** example the weighted sum is simply:",
        "```python",
        "z = w[0] * input_A + w[1] * input_B + b",
        "```",
        "",
        "But we have **4 examples**.  Instead of looping, we use matrix multiplication:",
        "```python",
        "# X has shape (4, 2) — 4 rows, 2 columns (one column per feature)",
        "# w has shape (2,)   — one weight per feature",
        "# X @ w computes the dot product for every row at once",
        "z = X @ w + b    # result shape: (4,) — one z-value per example",
        "```",
        "",
        "Think of it as doing the single-example formula 4 times simultaneously.",
    )),
    # Training loop OR
    md(lines(
        "## Training the Perceptron on OR",
        "",
        "**Cross-entropy loss** measures how far our probability predictions are  ",
        "from the true 0/1 labels — it penalises confident wrong answers heavily.",
        "",
        "**Gradient for the weights:**  ",
        "Each weight `w[j]` should change by how much it contributed to the error,  ",
        "averaged across all training examples:",
        "```",
        "grad_w = (1/n) * Xᵀ · error",
        "```",
        "Where `error = predicted - actual`.  `Xᵀ` (X transposed) pairs each  ",
        "feature column with the corresponding errors across examples.",
    )),
    code(lines(
        "np.random.seed(0)",
        "w = np.random.randn(2) * 0.1   # small random starting weights",
        "b = 0.0",
        "",
        "learning_rate = 0.5",
        "loss_history_or = []",
        "",
        "for step in range(1000):",
        "    # --- Forward pass ---",
        "    z = X @ w + b              # weighted sum for all 4 examples at once",
        "    y_hat = sigmoid(z)         # predicted probabilities",
        "",
        "    # --- Cross-entropy loss ---",
        "    loss = -np.mean(",
        "        y_or * np.log(y_hat + 1e-9) + (1 - y_or) * np.log(1 - y_hat + 1e-9)",
        "    )",
        "    loss_history_or.append(loss)",
        "",
        "    # --- Backward pass (gradients) ---",
        "    error = y_hat - y_or                   # how wrong are we per example?",
        "    grad_w = X.T @ error / len(X)          # weight gradient: error × feature, averaged",
        "    grad_b = error.mean()                  # bias gradient: plain average of errors",
        "",
        "    # --- Update ---",
        "    w -= learning_rate * grad_w",
        "    b -= learning_rate * grad_b",
        "",
        "print('Trained! OR predictions:')",
        "for inputs, expected in zip(X, y_or):",
        "    pred = sigmoid(inputs @ w + b)",
        "    print(f'  {inputs[0]} OR {inputs[1]}  → {pred:.3f}  (expected {expected})')",
    )),
    # Loss curve
    code(lines(
        "plt.figure(figsize=(8, 3))",
        'plt.plot(loss_history_or, color="darkorange")',
        'plt.xlabel("Training step")',
        'plt.ylabel("Cross-entropy loss")',
        'plt.title("OR perceptron — loss during training")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Decision boundary
    md(lines(
        "## Visualising the Decision Boundary",
        "",
        "A trained perceptron draws a **straight line** (in 2-D) that separates  ",
        "class 0 from class 1.  Let's plot it.",
    )),
    code(lines(
        "# Background colour map",
        "xx, yy = np.meshgrid(np.linspace(-0.3, 1.3, 200),",
        "                     np.linspace(-0.3, 1.3, 200))",
        "grid = np.c_[xx.ravel(), yy.ravel()]",
        "probs = sigmoid(grid @ w + b).reshape(xx.shape)",
        "",
        "plt.figure(figsize=(5, 5))",
        'plt.contourf(xx, yy, probs, levels=50, cmap="RdYlGn", alpha=0.7)',
        'plt.colorbar(label="P(OR = 1)")',
        "",
        "for (a, b_pt), label in zip(X, y_or):",
        '    color = "green" if label == 1 else "red"',
        '    marker = "o" if label == 1 else "s"',
        "    plt.scatter(a, b_pt, c=color, marker=marker, s=150,",
        '               edgecolors="black", linewidths=1.5, zorder=5)',
        "",
        'plt.xlim(-0.3, 1.3); plt.ylim(-0.3, 1.3)',
        'plt.xticks([0, 1]); plt.yticks([0, 1])',
        'plt.xlabel("Input A"); plt.ylabel("Input B")',
        'plt.title("Decision boundary for OR")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    # AND gate
    md(lines(
        "## The AND Gate",
        "",
        "AND is true only when **both** inputs are 1.  Let's train quickly.",
    )),
    code(lines(
        "y_and = np.array([0, 0, 0, 1])",
        "",
        "np.random.seed(0)",
        "w2 = np.random.randn(2) * 0.1",
        "b2 = 0.0",
        "",
        "for _ in range(1000):",
        "    z = X @ w2 + b2",
        "    y_hat = sigmoid(z)",
        "    error = y_hat - y_and",
        "    w2 -= learning_rate * (X.T @ error / len(X))",
        "    b2 -= learning_rate * error.mean()",
        "",
        "print('AND predictions:')",
        "for inputs, expected in zip(X, y_and):",
        "    pred = sigmoid(inputs @ w2 + b2)",
        "    print(f'  {inputs[0]} AND {inputs[1]}  → {pred:.3f}  (expected {expected})')",
    )),
    # XOR challenge
    md(lines(
        "## The XOR Challenge — Where a Single Neuron Fails",
        "",
        "XOR is 1 when **exactly one** input is 1:",
        "",
        "| A | B | A XOR B |",
        "|---|---|---------|",
        "| 0 | 0 |    0    |",
        "| 0 | 1 |    1    |",
        "| 1 | 0 |    1    |",
        "| 1 | 1 |    0    |",
        "",
        "A single neuron can only draw a **straight line** to separate classes.  ",
        "But XOR is not linearly separable — no single line can separate  ",
        "the two groups below. That's why we need **multiple layers** (Chapter 04).",
    )),
    code(lines(
        "y_xor = np.array([0, 1, 1, 0])",
        "",
        "# Train anyway and see the best it can do",
        "np.random.seed(0)",
        "w3 = np.random.randn(2) * 0.1",
        "b3 = 0.0",
        "for _ in range(5000):",
        "    z = X @ w3 + b3",
        "    y_hat = sigmoid(z)",
        "    error = y_hat - y_xor",
        "    w3 -= learning_rate * (X.T @ error / len(X))",
        "    b3 -= learning_rate * error.mean()",
        "",
        "print('XOR predictions (single neuron — watch it struggle):')",
        "for inputs, expected in zip(X, y_xor):",
        "    pred = sigmoid(inputs @ w3 + b3)",
        "    print(f'  {inputs[0]} XOR {inputs[1]}  → {pred:.3f}  (expected {expected})')",
        "",
        "# Show why: plot the decision boundary",
        "probs_xor = sigmoid(grid @ w3 + b3).reshape(xx.shape)",
        "plt.figure(figsize=(5, 5))",
        'plt.contourf(xx, yy, probs_xor, levels=50, cmap="RdYlGn", alpha=0.7)',
        'plt.colorbar(label="P(XOR = 1)")',
        "for (a, bpt), label in zip(X, y_xor):",
        '    color = "green" if label == 1 else "red"',
        '    marker = "o" if label == 1 else "s"',
        "    plt.scatter(a, bpt, c=color, marker=marker, s=150,",
        '               edgecolors="black", linewidths=1.5, zorder=5)',
        'plt.xlim(-0.3, 1.3); plt.ylim(-0.3, 1.3)',
        'plt.xticks([0, 1]); plt.yticks([0, 1])',
        'plt.xlabel("Input A"); plt.ylabel("Input B")',
        'plt.title("XOR — no straight line can separate the two classes!")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    md(lines(
        "## Key Lesson",
        "",
        "- A perceptron can learn **linearly separable** problems (OR, AND) perfectly.",
        "- It fails on **non-linear** problems like XOR.",
        "- The fix: stack multiple neurons in **layers** → a neural network (next notebook!).",
    )),
])
save(f"{BASE}/03_perceptron.ipynb", nb03)

# =============================================================================
# 04 — Neural Net from Scratch
# =============================================================================
nb04 = notebook([
    md(lines(
        "# 04 — Neural Network from Scratch",
        "",
        "## Why Do We Need Layers?",
        "",
        "A single perceptron can only draw a straight line.  XOR isn't straight.  ",
        "But if we **stack neurons in layers**, each layer can reshape the decision  ",
        "boundary — and together they can learn any function.",
        "",
        "This notebook builds a tiny neural network with:",
        "- **Input layer**: 2 inputs (A and B)",
        "- **Hidden layer**: 3 neurons (they learn useful internal representations)",
        "- **Output layer**: 1 neuron (predicts XOR)",
        "",
        "We write every calculation by hand so you can see exactly what PyTorch  ",
        "(and TensorFlow, etc.) are doing under the hood.",
    )),
    # XOR dataset
    md(lines(
        "## The XOR Dataset",
        "",
        "| A | B | A XOR B |",
        "|---|---|---------|",
        "| 0 | 0 |    0    |",
        "| 0 | 1 |    1    |",
        "| 1 | 0 |    1    |",
        "| 1 | 1 |    0    |",
        "",
        "The '0,0→0' and '1,1→0' are on one side; '0,1→1' and '1,0→1' on the other.  ",
        "They're arranged in an X pattern — no straight line can separate them.",
    )),
    code(lines(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "%matplotlib inline",
        "",
        "def sigmoid(x):",
        "    return 1 / (1 + np.exp(-x))",
        "",
        "def sigmoid_d(x):",
        "    \"\"\"Derivative of sigmoid — used in backprop.\"\"\"",
        "    s = sigmoid(x)",
        "    return s * (1 - s)",
        "",
        "# 4 training examples, 2 features each",
        "X = np.array([[0, 0],",
        "              [0, 1],",
        "              [1, 0],",
        "              [1, 1]])",
        "",
        "# Target outputs (column vector for matrix math convenience)",
        "y = np.array([[0],",
        "              [1],",
        "              [1],",
        "              [0]])",
    )),
    # Architecture
    md(lines(
        "## Network Architecture",
        "",
        "```",
        "  Input         Hidden (3 neurons)    Output",
        "  ─────         ──────────────────    ──────",
        "  A (x₁) ─────→  H₁                  ↗",
        "         ╲  ╱──→  H₂  ──────────────→  Ŷ",
        "  B (x₂) ─────→  H₃                  ↗",
        "```",
        "",
        "**Weights:**",
        "- `W1` shape `(2, 3)` — connects 2 inputs to 3 hidden neurons  ",
        "  (2 rows × 3 columns = 6 weights)",
        "- `W2` shape `(3, 1)` — connects 3 hidden neurons to 1 output  ",
        "  (3 rows × 1 column = 3 weights)",
        "- `b1` shape `(1, 3)` — one bias per hidden neuron",
        "- `b2` shape `(1, 1)` — one bias for the output neuron",
        "",
        "**Why small random weights?**  If all weights start at 0, every neuron  ",
        "computes the same thing and learns identically — they never differentiate.  ",
        "Small random values break this symmetry.",
    )),
    code(lines(
        "np.random.seed(42)",
        "W1 = np.random.randn(2, 3) * 0.5   # (inputs × hidden)",
        "b1 = np.zeros((1, 3))              # one bias per hidden neuron",
        "W2 = np.random.randn(3, 1) * 0.5   # (hidden × output)",
        "b2 = np.zeros((1, 1))              # one bias for the output",
        "",
        'print("W1 (input → hidden):")',
        "print(W1)",
        'print("\\nW2 (hidden → output):")',
        "print(W2)",
    )),
    # Forward pass
    md(lines(
        "## Forward Pass",
        "",
        "Data flows **forward** through the network: inputs → hidden layer → output.",
        "",
        "Each layer does two things:",
        "1. **Linear combination**: `z = X · W + b`",
        "2. **Activation**: `a = sigmoid(z)` — adds non-linearity",
        "",
        "Without the sigmoid, stacking layers would just be one big linear function  ",
        "— no more expressive than a single neuron.",
    )),
    code(lines(
        "# --- Hidden layer ---",
        "# z1 shape: (4, 3) — one row per example, one column per hidden neuron",
        "z1 = X @ W1 + b1      # linear combination",
        "a1 = sigmoid(z1)      # activation — each hidden neuron's output",
        "",
        "# --- Output layer ---",
        "# z2 shape: (4, 1) — one prediction per example",
        "z2 = a1 @ W2 + b2     # linear combination using hidden outputs",
        "a2 = sigmoid(z2)      # final prediction (probability)",
        "",
        'print("Initial predictions (before any training):")',
        "for i, (inputs, pred, true) in enumerate(zip(X, a2, y)):",
        "    print(f'  {inputs[0]} XOR {inputs[1]}  → {pred[0]:.3f}  (true: {true[0]})')",
    )),
    # Loss
    md(lines(
        "## Loss Function — Mean Squared Error",
        "",
        "We use MSE here (same as linear regression) for simplicity:",
        "",
        "```",
        "loss = mean( (predicted − true)² )",
        "```",
    )),
    code(lines(
        "loss = ((a2 - y) ** 2).mean()",
        "print(f'Initial loss: {loss:.4f}')",
        "print('(0 would be perfect, 0.25 is terrible for this problem)')",
    )),
    # Backward pass — detailed
    md(lines(
        "## Backward Pass — Backpropagation",
        "",
        "This is where the magic happens.  We apply the **chain rule** of calculus  ",
        "to figure out how each weight contributed to the error.",
        "",
        "We work **backwards** from the output:",
        "",
        "```",
        "Loss → output neuron → hidden neurons → input weights",
        "```",
        "",
        "### Output layer gradients",
        "",
        "**Step 1 — How does loss change with output activation `a2`?**",
        "```python",
        "d_a2 = 2 * (a2 - y) / n      # derivative of MSE",
        "```",
        "",
        "**Step 2 — How does loss change with the pre-activation `z2`?**  ",
        "We multiply by the sigmoid's derivative (chain rule through sigmoid):",
        "```python",
        "d_z2 = d_a2 * sigmoid_d(z2)",
        "```",
        "",
        "**Step 3 — How does loss change with weight matrix `W2`?**  ",
        "Each weight in W2 is multiplied by a hidden activation in the forward pass,  ",
        "so we reverse that with a transpose:",
        "```python",
        "d_W2 = a1.T @ d_z2",
        "```",
        "",
        "**Step 4 — How does loss change with bias `b2`?**  ",
        "The bias adds to every example equally, so we just sum the error signal:",
        "```python",
        "d_b2 = d_z2.sum(axis=0, keepdims=True)",
        "```",
        "",
        "### Hidden layer gradients",
        "",
        "**Step 5 — Pass the error signal back through W2 to reach hidden neurons:**",
        "```python",
        "d_a1 = d_z2 @ W2.T",
        "```",
        "",
        "**Step 6 — Chain rule through the hidden sigmoid:**",
        "```python",
        "d_z1 = d_a1 * sigmoid_d(z1)",
        "```",
        "",
        "**Steps 7 & 8 — Gradients for W1 and b1 (same pattern as output layer):**",
        "```python",
        "d_W1 = X.T @ d_z1",
        "d_b1 = d_z1.sum(axis=0, keepdims=True)",
        "```",
    )),
    # Training loop
    md(lines(
        "## Training Loop — 5000 Steps",
        "",
        "Now we run forward + backward pass 5000 times, updating weights each time.",
    )),
    code(lines(
        "# Re-initialise weights",
        "np.random.seed(42)",
        "W1 = np.random.randn(2, 3) * 0.5",
        "b1 = np.zeros((1, 3))",
        "W2 = np.random.randn(3, 1) * 0.5",
        "b2 = np.zeros((1, 1))",
        "",
        "learning_rate = 0.5",
        "losses = []",
        "n = len(X)",
        "",
        "for step in range(5000):",
        "    # --- Forward pass ---",
        "    z1 = X @ W1 + b1",
        "    a1 = sigmoid(z1)",
        "    z2 = a1 @ W2 + b2",
        "    a2 = sigmoid(z2)",
        "",
        "    # --- Loss ---",
        "    loss = ((a2 - y) ** 2).mean()",
        "    losses.append(loss)",
        "",
        "    # --- Backward pass ---",
        "    # Output layer",
        "    d_a2 = 2 * (a2 - y) / n          # gradient of loss w.r.t. a2",
        "    d_z2 = d_a2 * sigmoid_d(z2)      # chain rule through sigmoid",
        "    d_W2 = a1.T @ d_z2               # gradient for output weights",
        "    d_b2 = d_z2.sum(axis=0, keepdims=True)   # gradient for output bias",
        "",
        "    # Hidden layer",
        "    d_a1 = d_z2 @ W2.T               # error signal flowing back through W2",
        "    d_z1 = d_a1 * sigmoid_d(z1)      # chain rule through hidden sigmoid",
        "    d_W1 = X.T @ d_z1               # gradient for hidden weights",
        "    d_b1 = d_z1.sum(axis=0, keepdims=True)   # gradient for hidden bias",
        "",
        "    # --- Update weights ---",
        "    W2 -= learning_rate * d_W2",
        "    b2 -= learning_rate * d_b2",
        "    W1 -= learning_rate * d_W1",
        "    b1 -= learning_rate * d_b1",
        "",
        "print(f'Final loss: {losses[-1]:.6f}')",
    )),
    # Results
    code(lines(
        "print('XOR predictions after training:')",
        "for inputs, pred, true in zip(X, a2, y):",
        "    print(f'  {inputs[0]} XOR {inputs[1]}  → {pred[0]:.3f}  (expected {true[0]})')",
        "",
        "plt.figure(figsize=(8, 3))",
        'plt.plot(losses, color="purple")',
        'plt.xlabel("Training step")',
        'plt.ylabel("MSE loss")',
        'plt.title("Neural network learning XOR")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Decision boundary
    md(lines(
        "## Visualising the Decision Boundary",
        "",
        "Unlike the single perceptron, the network can form a **curved** boundary  ",
        "that correctly separates the XOR classes.",
    )),
    code(lines(
        "xx, yy = np.meshgrid(np.linspace(-0.3, 1.3, 200),",
        "                     np.linspace(-0.3, 1.3, 200))",
        "grid = np.c_[xx.ravel(), yy.ravel()]",
        "",
        "# Forward pass on the grid",
        "g_z1 = grid @ W1 + b1",
        "g_a1 = sigmoid(g_z1)",
        "g_z2 = g_a1 @ W2 + b2",
        "g_probs = sigmoid(g_z2).reshape(xx.shape)",
        "",
        "plt.figure(figsize=(5, 5))",
        'plt.contourf(xx, yy, g_probs, levels=50, cmap="RdYlGn", alpha=0.7)',
        'plt.colorbar(label="P(XOR = 1)")',
        "",
        "y_flat = y.flatten()",
        "for (a, b_pt), label in zip(X, y_flat):",
        '    color = "green" if label == 1 else "red"',
        '    marker = "o" if label == 1 else "s"',
        "    plt.scatter(a, b_pt, c=color, marker=marker, s=150,",
        '               edgecolors="black", linewidths=1.5, zorder=5)',
        "",
        'plt.xlim(-0.3, 1.3); plt.ylim(-0.3, 1.3)',
        'plt.xticks([0, 1]); plt.yticks([0, 1])',
        'plt.xlabel("Input A"); plt.ylabel("Input B")',
        'plt.title("Neural network decision boundary — XOR solved!")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    md(lines(
        "## Key Lessons",
        "",
        "1. **Hidden layers** allow the network to learn non-linear decision boundaries.",
        "2. **Backpropagation** is just the chain rule applied layer by layer, backwards.",
        "3. Every gradient tells a weight: 'if you increase, does the loss go up or down?'",
        "4. Writing this by hand reveals exactly what PyTorch `loss.backward()` computes  ",
        "   automatically — next notebook!",
    )),
])
save(f"{BASE}/04_neural_net_scratch.ipynb", nb04)

# =============================================================================
# 06 — PyTorch Tensors
# =============================================================================
nb06 = notebook([
    md(lines(
        "# 06 — PyTorch Tensors & Autograd",
        "",
        "## Why PyTorch After NumPy?",
        "",
        "In the previous notebooks we computed gradients by hand — tedious and  ",
        "error-prone for big networks. **PyTorch** automates gradient computation  ",
        "while feeling almost identical to NumPy for basic operations.",
        "",
        "The key addition is **autograd**: PyTorch tracks every operation on a tensor  ",
        "and can automatically differentiate through the whole computation graph.",
        "",
        "We'll cover:",
        "1. Tensor basics (NumPy you already know)",
        "2. Autograd — automatic gradient computation",
        "3. Linear regression using autograd (no hand-derived formulas!)",
        "4. GPU support",
    )),
    # Part 1
    md(lines(
        "## Part 1 — Tensor Basics",
        "",
        "A PyTorch `Tensor` behaves just like a NumPy array.  Most operations  ",
        "are identical; the names just changed slightly.",
    )),
    code(lines(
        "import torch",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "%matplotlib inline",
        "",
        "a = torch.tensor([1.0, 2.0, 3.0])",
        "b = torch.tensor([4.0, 5.0, 6.0])",
        "",
        "print(f'a         = {a}')",
        "print(f'b         = {b}')",
        "print(f'a + b     = {a + b}')",
        "print(f'a * b     = {a * b}')",
        "print(f'a.mean()  = {a.mean()}')",
        "",
        "matrix = torch.zeros(3, 4)",
        "print(f'\\ntorch.zeros(3, 4): shape = {matrix.shape}')",
        "print(matrix)",
    )),
    code(lines(
        "# NumPy ↔ PyTorch interop (they share memory — zero copy!)",
        "np_array = np.array([1.0, 2.0, 3.0])",
        "tensor   = torch.from_numpy(np_array)",
        "back     = tensor.numpy()",
        "",
        "print(f'NumPy array : {np_array}')",
        "print(f'As tensor   : {tensor}')",
        "print(f'Back to NumPy: {back}')",
        "print()",
        "print('They share memory — modifying one changes the other:')",
        "np_array[0] = 99.0",
        "print(f'  np_array[0] = 99, tensor = {tensor}')",
    )),
    # Part 2
    md(lines(
        "## Part 2 — Autograd: Automatic Gradient Computation",
        "",
        "Mark a tensor with `requires_grad=True` and PyTorch will track every  ",
        "operation on it.  When you call `.backward()`, it computes all gradients  ",
        "automatically via the chain rule.",
        "",
        "**Example:** `y = w·x² + 5`  ",
        "The derivative with respect to `w` is: `dy/dw = x²`",
    )),
    code(lines(
        "w = torch.tensor(2.0, requires_grad=True)   # parameter we want to differentiate",
        "x = torch.tensor(3.0)                        # input (fixed)",
        "",
        "y = w * x**2 + 5",
        "",
        "print(f'y = w * x² + 5  where w={w.item()}, x={x.item()}')",
        "print(f'y = {y.item()}')",
        "",
        "# Ask PyTorch to compute dy/dw",
        "y.backward()",
        "",
        "print(f'\\ndy/dw computed by PyTorch : {w.grad.item()}')",
        "print(f'dy/dw by hand (= x² = 9) : 9.0')",
    )),
    # Part 3
    md(lines(
        "## Part 3 — Linear Regression with Autograd",
        "",
        "Previously we derived the gradient formulas for `w` and `b` by hand.  ",
        "Now PyTorch does it for us — we just define the loss and call `.backward()`.",
        "",
        "Same dataset as notebook 02.",
    )),
    code(lines(
        "np.random.seed(42)",
        "x_np = np.linspace(0, 10, 30)",
        "y_np = 10 * x_np + 30 + np.random.randn(30) * 8",
        "",
        "x_t = torch.tensor(x_np, dtype=torch.float32)",
        "y_t = torch.tensor(y_np, dtype=torch.float32)",
        "",
        "# Visualise the data",
        "plt.figure(figsize=(7, 4))",
        'plt.scatter(x_np, y_np, color="steelblue", label="data")',
        'plt.xlabel("x"); plt.ylabel("y")',
        'plt.title("Dataset for linear regression")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    code(lines(
        "w = torch.tensor(0.0, requires_grad=True)",
        "b = torch.tensor(0.0, requires_grad=True)",
        "",
        "learning_rate = 0.01",
        "losses = []",
        "",
        "for step in range(200):",
        "    # Forward pass",
        "    y_pred = w * x_t + b",
        "    loss   = ((y_pred - y_t) ** 2).mean()",
        "",
        "    # Backward pass — PyTorch computes dLoss/dw and dLoss/db",
        "    loss.backward()",
        "",
        "    # Update — we must tell PyTorch NOT to track these operations",
        "    with torch.no_grad():",
        "        w -= learning_rate * w.grad",
        "        b -= learning_rate * b.grad",
        "",
        "    # Clear gradients (they accumulate by default)",
        "    w.grad.zero_()",
        "    b.grad.zero_()",
        "",
        "    losses.append(loss.item())",
        "",
        "print(f'Learned : y = {w.item():.2f} * x + {b.item():.2f}')",
        "print(f'Truth   : y = 10.00 * x + 30.00')",
    )),
    code(lines(
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))",
        "",
        "# Fitted line",
        'ax1.scatter(x_np, y_np, color="steelblue", label="data")',
        "x_line = np.array([0.0, 10.0])",
        "y_line = w.item() * x_line + b.item()",
        'ax1.plot(x_line, y_line, color="crimson", linewidth=2, label="fitted line")',
        'ax1.set_xlabel("x"); ax1.set_ylabel("y")',
        'ax1.set_title(f"Result: y = {w.item():.1f}x + {b.item():.1f}")',
        "ax1.legend()",
        "",
        "# Loss curve",
        'ax2.plot(losses, color="darkorange")',
        'ax2.set_xlabel("step"); ax2.set_ylabel("MSE loss")',
        'ax2.set_title("Loss curve")',
        "",
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Part 4
    md(lines(
        "## Part 4 — GPU Support",
        "",
        "One of PyTorch's biggest advantages: move tensors to the GPU with `.to(device)`  ",
        "and the exact same code runs (potentially 100× faster) on GPU hardware.",
    )),
    code(lines(
        'device = "cuda" if torch.cuda.is_available() else "cpu"',
        "print(f'Device available: {device}')",
        "",
        "# To run on GPU (if available):",
        "# x_t = x_t.to(device)",
        "# y_t = y_t.to(device)",
        "# w   = torch.tensor(0.0, requires_grad=True, device=device)",
        "# ... rest of the code is identical",
        "",
        'if device == "cpu":',
        '    print("No GPU found — that\'s fine, all our examples are tiny.")',
        "else:",
        '    print("GPU ready! Real models can train dramatically faster on CUDA.")',
    )),
    md(lines(
        "## Key Lessons",
        "",
        "1. **Tensors** are almost identical to NumPy arrays — switch costs are low.",
        "2. **`requires_grad=True`** tells PyTorch to track operations for differentiation.",
        "3. **`.backward()`** computes all gradients automatically — no hand-derived formulas.",
        "4. **`torch.no_grad()`** prevents PyTorch from tracking the weight-update step.",
        "5. **GPU acceleration** is one `.to('cuda')` call away.",
    )),
])
save(f"{BASE}/06_pytorch_tensors.ipynb", nb06)

# =============================================================================
# 07 — PyTorch nn.Module
# =============================================================================
nb07 = notebook([
    md(lines(
        "# 07 — PyTorch `nn.Module`: The Clean Way to Build Networks",
        "",
        "## Same Network, Cleaner Code",
        "",
        "In notebook 04 we managed W1, b1, W2, b2 as separate variables and wrote  ",
        "every gradient update by hand.",
        "",
        "PyTorch's `nn.Module` system lets us:",
        "- **Declare the architecture** in a class",
        "- **Let PyTorch track parameters** (no more W1, b1, ...)",
        "- **Use `optimizer.step()`** instead of manual weight updates",
        "",
        "We'll solve XOR again — same problem, maybe 3× less code.",
    )),
    code(lines(
        "import torch",
        "import torch.nn as nn",
        "import torch.optim as optim",
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "%matplotlib inline",
        "",
        "# XOR dataset",
        "X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])",
        "y = torch.tensor([[0.], [1.], [1.], [0.]])",
    )),
    md(lines(
        "## Defining the Network",
        "",
        "We subclass `nn.Module` and define:",
        "- **`__init__`** — create the layers",
        "- **`forward`** — describe how data flows through them",
        "",
        "PyTorch automatically discovers all parameters (weights + biases)  ",
        "inside `nn.Linear` layers.",
        "",
        "`nn.Linear(in, out)` creates a fully-connected layer:  ",
        "it holds a weight matrix of shape `(in, out)` and a bias vector of size `out`.",
    )),
    code(lines(
        "class XORNet(nn.Module):",
        "    def __init__(self):",
        "        super().__init__()",
        "        # 2 inputs → 3 hidden neurons",
        "        self.hidden = nn.Linear(2, 3)",
        "        # 3 hidden neurons → 1 output",
        "        self.output = nn.Linear(3, 1)",
        "",
        "    def forward(self, x):",
        "        x = torch.sigmoid(self.hidden(x))   # hidden layer + activation",
        "        x = torch.sigmoid(self.output(x))   # output layer + activation",
        "        return x",
        "",
        "model = XORNet()",
        "print('Network architecture:')",
        "print(model)",
        "print()",
        "total_params = sum(p.numel() for p in model.parameters())",
        "print(f'Total trainable parameters: {total_params}')",
        "print('  (W1: 2×3=6, b1: 3, W2: 3×1=3, b2: 1  → 6+3+3+1 = 13)')",
    )),
    md(lines(
        "## The Training Loop: Three Standard Steps",
        "",
        "Every PyTorch training loop follows the same pattern:",
        "",
        "```python",
        "# 1. Forward pass — compute predictions",
        "y_pred = model(X)",
        "loss   = criterion(y_pred, y)",
        "",
        "# 2. Backward pass — compute gradients",
        "optimizer.zero_grad()   # clear old gradients first!",
        "loss.backward()         # compute new gradients",
        "",
        "# 3. Update — nudge every parameter in the right direction",
        "optimizer.step()",
        "```",
        "",
        "We use **SGD** (Stochastic Gradient Descent) with `lr=0.5`, same as before.  ",
        "The **MSELoss** criterion computes Mean Squared Error for us.",
    )),
    code(lines(
        "criterion = nn.MSELoss()",
        "optimizer = optim.SGD(model.parameters(), lr=0.5)",
        "",
        "losses = []",
        "",
        "for step in range(5000):",
        "    # 1. Forward",
        "    y_pred = model(X)",
        "    loss   = criterion(y_pred, y)",
        "",
        "    # 2. Backward",
        "    optimizer.zero_grad()   # always clear before backward!",
        "    loss.backward()",
        "",
        "    # 3. Update",
        "    optimizer.step()",
        "",
        "    losses.append(loss.item())",
        "",
        "print(f'Final loss: {losses[-1]:.6f}')",
    )),
    # Results
    code(lines(
        "print('XOR predictions after training:')",
        "with torch.no_grad():",
        "    preds = model(X)",
        "",
        "for inputs, pred, expected in zip(X, preds, y):",
        "    a, b = int(inputs[0]), int(inputs[1])",
        "    print(f'  {a} XOR {b}  → {pred.item():.3f}  (expected {int(expected.item())})')",
    )),
    code(lines(
        "plt.figure(figsize=(8, 3))",
        'plt.plot(losses, color="mediumseagreen")',
        'plt.xlabel("Training step")',
        'plt.ylabel("MSE loss")',
        'plt.title("XOR with nn.Module — loss curve")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    # Decision boundary
    md(lines(
        "## Decision Boundary",
    )),
    code(lines(
        "xx, yy = np.meshgrid(np.linspace(-0.3, 1.3, 200),",
        "                     np.linspace(-0.3, 1.3, 200))",
        "grid_np = np.c_[xx.ravel(), yy.ravel()].astype(np.float32)",
        "grid_t  = torch.tensor(grid_np)",
        "",
        "with torch.no_grad():",
        "    probs = model(grid_t).numpy().reshape(xx.shape)",
        "",
        "plt.figure(figsize=(5, 5))",
        'plt.contourf(xx, yy, probs, levels=50, cmap="RdYlGn", alpha=0.7)',
        'plt.colorbar(label="P(XOR = 1)")',
        "",
        "y_flat = y.numpy().flatten()",
        "X_np   = X.numpy()",
        "for (a, b_pt), label in zip(X_np, y_flat):",
        '    color = "green" if label == 1 else "red"',
        '    marker = "o" if label == 1 else "s"',
        "    plt.scatter(a, b_pt, c=color, marker=marker, s=150,",
        '               edgecolors="black", linewidths=1.5, zorder=5)',
        "",
        'plt.xlim(-0.3, 1.3); plt.ylim(-0.3, 1.3)',
        'plt.xticks([0, 1]); plt.yticks([0, 1])',
        'plt.xlabel("Input A"); plt.ylabel("Input B")',
        'plt.title("nn.Module XOR — decision boundary")',
        "plt.tight_layout()",
        "plt.show()",
    )),
    md(lines(
        "## Key Lessons",
        "",
        "1. **`nn.Module`** packages weights into a reusable, inspectable object.",
        "2. **`nn.Linear`** handles weights and biases for a fully-connected layer.",
        "3. The **three-step loop** (forward → zero_grad → backward → step)  ",
        "   is the universal PyTorch training pattern.",
        "4. Real models (ResNets, Transformers) use the exact same loop —  ",
        "   just with much larger architectures.",
    )),
])
save(f"{BASE}/07_pytorch_nn.ipynb", nb07)

# =============================================================================
# 10 — LLM + Pydantic AI
# =============================================================================
nb10 = notebook([
    md(lines(
        "# 10 — LLMs + Pydantic AI: Structured Outputs from Language Models",
        "",
        "## What This Notebook Covers",
        "",
        "Large Language Models (LLMs) like Llama 3 can answer almost any question —  ",
        "but by default they return *free text*.  For real applications we often want  ",
        "**structured, typed data** that our code can work with reliably.",
        "",
        "**Pydantic AI** is a Python library that lets you:",
        "- Talk to an LLM with a simple Agent API",
        "- Declare a Pydantic model as the *expected output type*",
        "- Receive a validated Python object (not a raw string)",
        "",
        "We use **Ollama** to run Llama 3.2 locally (no API key required).",
        "",
        "> **Prerequisite:** Ollama must be running locally.  ",
        "> Start it with: `ollama serve` and ensure `llama3.2` is pulled.",
    )),
    md(lines(
        "## Setup",
    )),
    code(lines(
        "from pydantic import BaseModel, Field",
        "from pydantic_ai import Agent",
        "from pydantic_ai.models.openai import OpenAIChatModel",
        "from pydantic_ai.providers.ollama import OllamaProvider",
        "",
        "MODEL_NAME = 'llama3.2'",
        "",
        "# Connect to the locally-running Ollama server",
        "ollama_model = OpenAIChatModel(",
        "    model_name=MODEL_NAME,",
        "    provider=OllamaProvider(base_url='http://localhost:11434/v1'),",
        ")",
        "",
        "print(f'Using model: {MODEL_NAME} via Ollama')",
    )),
    # Demo 1
    md(lines(
        "## Demo 1 — Plain Text Response",
        "",
        "The simplest usage: send a question, get a text answer.",
    )),
    code(lines(
        "plain_agent = Agent(ollama_model)",
        "",
        "result = plain_agent.run_sync(",
        "    'Explain what a neural network is in 2 sentences, as if talking to a 10-year-old.'",
        ")",
        "",
        "print('Answer:')",
        "print(result.output)",
    )),
    # Demo 2
    md(lines(
        "## Demo 2 — Structured Output with Pydantic",
        "",
        "Instead of free text, we define a Pydantic model that describes exactly  ",
        "what fields we want — and Pydantic AI ensures the LLM fills them all in.",
        "",
        "This is powerful for building apps: you can pass `explanation.difficulty`  ",
        "to filter content, or display `explanation.real_world_analogy` in a UI.",
    )),
    code(lines(
        "class ConceptExplanation(BaseModel):",
        '    concept:           str = Field(description="The AI concept being explained")',
        '    one_line_summary:  str = Field(description="What it is in one sentence")',
        '    real_world_analogy: str = Field(description="An analogy a non-technical person would understand")',
        '    example:           str = Field(description="A concrete example (2-3 sentences)")',
        '    difficulty:        str = Field(description="Beginner / Intermediate / Advanced")',
        "",
        "",
        "structured_agent = Agent(ollama_model, output_type=ConceptExplanation)",
        "",
        "concepts = ['gradient descent', 'overfitting', 'neural network']",
        "",
        "for concept in concepts:",
        "    result = structured_agent.run_sync(",
        "        f'Explain the following AI concept for a beginner: {concept}'",
        "    )",
        "    e = result.output",
        "    print(f'--- {e.concept} ({e.difficulty}) ---')",
        "    print(f'Summary : {e.one_line_summary}')",
        "    print(f'Analogy : {e.real_world_analogy}')",
        "    print(f'Example : {e.example}')",
        "    print()",
    )),
    # Demo 3
    md(lines(
        "## Demo 3 — Quiz Question Generator",
        "",
        "We define a `QuizQuestion` model and give the agent a system prompt  ",
        "that shapes its personality.  Each call returns a ready-to-use quiz question  ",
        "with options, the correct answer index, and an explanation.",
    )),
    code(lines(
        "class QuizQuestion(BaseModel):",
        "    question:             str",
        "    options:              list[str] = Field(description='Exactly 4 multiple choice options')",
        "    correct_option_index: int       = Field(description='0-based index of the correct option')",
        "    explanation:          str",
        "",
        "",
        "quiz_agent = Agent(",
        "    ollama_model,",
        "    output_type=QuizQuestion,",
        "    system_prompt=(",
        "        'You are a friendly AI teacher. '",
        "        'Generate short, clear multiple-choice quiz questions '",
        "        'about basic AI and machine learning concepts.'",
        "    ),",
        ")",
        "",
        "topics = ['What gradient descent does', 'What overfitting means']",
        "",
        "for topic in topics:",
        "    result = quiz_agent.run_sync(f'Create a quiz question about: {topic}')",
        "    q = result.output",
        "    print(f'Q: {q.question}')",
        "    for i, opt in enumerate(q.options):",
        "        marker = '✓' if i == q.correct_option_index else ' '",
        "        print(f'  [{marker}] {i + 1}. {opt}')",
        "    print(f'  → {q.explanation}')",
        "    print()",
    )),
    md(lines(
        "## Key Lessons",
        "",
        "1. **LLMs produce text** — but with Pydantic AI you can get **typed Python objects**.",
        "2. **`output_type=MyModel`** tells the agent what schema to fill in.  ",
        "   Under the hood it uses structured outputs / function calling.",
        "3. **System prompts** shape the model's personality and focus.",
        "4. **Ollama** lets you run powerful open models locally — no API key, no cost.",
        "5. This pattern (define schema → call LLM → use structured data) is increasingly  ",
        "   common in production AI applications.",
    )),
])
save(f"{BASE}/10_llm_pydantic_ai.ipynb", nb10)

print("\nAll notebooks created successfully.")
